In [2]:
import numpy as np

In [5]:
a = np.array([[1,2,3],[3,4,5]])

In [6]:
a + 1 

array([[2, 3, 4],
       [4, 5, 6]])

In [7]:
a * a

array([[ 1,  4,  9],
       [ 9, 16, 25]])

In [8]:
# изменяем оригинальный массив
a.resize(6,1)

In [9]:
a

array([[1],
       [2],
       [3],
       [3],
       [4],
       [5]])

In [12]:
# не изменяем оригинальный массив
b = a.reshape(1,6)
a, b

(array([[1],
        [2],
        [3],
        [3],
        [4],
        [5]]), array([[1, 2, 3, 3, 4, 5]]))

In [13]:
np.cos(a)

array([[ 0.54030231],
       [-0.41614684],
       [-0.9899925 ],
       [-0.9899925 ],
       [-0.65364362],
       [ 0.28366219]])

In [16]:
a.min(axis=0)

array([1])

In [24]:
c = np.eye(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
c = np.linspace(0,100)
c

array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])

In [28]:
def f1(i, j):
    return 33 * i + j

np.fromfunction(f1,(2,4))

array([[ 0.,  1.,  2.,  3.],
       [33., 34., 35., 36.]])

In [32]:
#указываем -1 для авторасчёта

c.reshape((5,-1))

array([[  0.        ,   2.04081633,   4.08163265,   6.12244898,
          8.16326531,  10.20408163,  12.24489796,  14.28571429,
         16.32653061,  18.36734694],
       [ 20.40816327,  22.44897959,  24.48979592,  26.53061224,
         28.57142857,  30.6122449 ,  32.65306122,  34.69387755,
         36.73469388,  38.7755102 ],
       [ 40.81632653,  42.85714286,  44.89795918,  46.93877551,
         48.97959184,  51.02040816,  53.06122449,  55.10204082,
         57.14285714,  59.18367347],
       [ 61.2244898 ,  63.26530612,  65.30612245,  67.34693878,
         69.3877551 ,  71.42857143,  73.46938776,  75.51020408,
         77.55102041,  79.59183673],
       [ 81.63265306,  83.67346939,  85.71428571,  87.75510204,
         89.79591837,  91.83673469,  93.87755102,  95.91836735,
         97.95918367, 100.        ]])

In [34]:
v = c.view()
v.base is c

True

In [35]:
cc = c.copy()

In [41]:
np.random.sample((2, 3))

array([[0.66408461, 0.82175592, 0.62176585],
       [0.53289251, 0.57799044, 0.92604798]])

In [42]:
np.random.uniform(2, 8, (2, 10))

array([[5.80005448, 7.30299082, 4.33254422, 2.82603906, 3.1183861 ,
        6.97253855, 5.35006041, 7.84715419, 7.78482299, 5.21690945],
       [4.50477647, 4.61664333, 5.37026214, 6.63347693, 3.6010994 ,
        3.91195107, 4.35783181, 7.31048617, 6.17090951, 6.92908683]])

In [47]:
numpy.info(numpy.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [43]:
print(np.__version__)
np.show_config()

1.14.0
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Alex/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\lib', 'C:/Users/Alex/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Alex/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\lib', '